theme: jekyll-theme-slate
title: Markov drummer - Markov chain-based drum pattern generator
description: Markov chain-based drum pattern generator
show_downloads: true

share-links-active:
  twitter: true
  facebook: true
  linkedin: true

github:
  zip_url: https://shorstok.github.io/markovdrummer/md.zip
  tar_url: https://shorstok.github.io/markovdrummer/md.zip